import React, { useEffect, useState } from "react";
import Head from "next/head";
import About5 from "../components/about/About5";
import Banner5 from "../components/banner/Banner5";
import Blog5 from "../components/blog/Blog5";
import JoinOurTeam from "../components/common/JoinOurTeam";
import Feature5 from "../components/feature/Feature5";
import Footer from "../components/footer/Footer";
import Header5 from "../components/header/Header5";
import Sponsoree5 from "../components/home5/Sponsoree5";
import Portfolio5 from "../components/portfolio/Portfolio5";
import Service5 from "../components/service/Service5";
import Team5 from "../components/team/Team5";
import Testimonial5 from "../components/testimonial/Testimonial5";
import Preloader from "../components/common/Preloader";
import Header from "../components/header/Header";

function Home5() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(false);
    setTimeout(() => {
      setLoading(true);
    }, 3000);
  }, []);

  return (
    <>
      {!loading ? (
        <Preloader style="home5preloader" />
      ) : (
        <>
          <Head>
            <title>Spinner - Corporate nextjs Template</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="assets/images/icons/favicon5.png" />
          </Head>
          <Header />
          <Banner5 />
          <About5 />
          <Sponsoree5 />
          <Service5 />
          <Portfolio5 />
          <Team5 />
          <Feature5 />
          <Testimonial5 />
          <Blog5 />
          <JoinOurTeam btnclass="btn--primary5" />
          <Footer
            footerStyle="style-5"
            footerImage="assets/images/icons/footer5-logo.svg"
          />
        </>
      )}
    </>
  );
}

export default Home5;
